export class Word {
  public furigana: string;
  public kanji: string;
  public type: string;
  public translation: string;

  constructor(furigana: string, kanji: string, type: string, translation: string){
    this.furigana = furigana;
    this.kanji = kanji;
    this.type = type;
    this.translation = translation;
  }
}

export interface IChoice {
  value: string;
  correct: boolean;
};

export let words: Array<Word> = [
  new Word('あ',  '',  'int',  'Ah'),
  new Word('ああ',  '',  'int',  'like that, that way'),
  new Word('あいさつ・する',  '',  'n,vs',  'greeting'),
  new Word('あいだ',  '間',  'n',  'space, interval'),
  new Word('あう',  '合う',  'u-v',  'to fit, to match'),
  new Word('あかちゃん',  '',  'n',  'baby, infant'),
  new Word('あがる',  '上がる',  'u-v',  'to rise, to go up'),
  new Word('あかんぼう',  '赤ん坊',  'n',  'baby'),
  new Word('あく',  '空く',  'u-v,vi',  'to open, to become empty'),
  new Word('アクセサリー',  '',  'n',  'accessory'),
  new Word('あげる',  '',  'ru-v',  'to give'),
  new Word('あさい',  '浅い',  'adj',  'shallow, superficial'),
  new Word('あじ',  '味',  'adj-na,n',  'flavor, taste'),
  new Word('アジア',  '',  'n',  'Asia'),
  new Word('あす',  '明日',  'n-t',  'tomorrow'),
  new Word('あそび',  '遊び',  'n,n-suf',  'play'),
  new Word('あつまる',  '集る',  'u-v',  'to gather, to collect'),
  new Word('あつめる',  '集める',  'ru-v,vt',  'to collect, to assemble'),
  new Word('アナウンサー',  '',  'n',  'announcer'),
  new Word('アフリカ',  '',  'n',  'Africa'),
  new Word('アメリカ',  '',  'n',  'America'),
  new Word('あやまる',  '謝る',  'u-v',  'to apologize'),
  new Word('アルコール',  '',  'n',  'alcohol'),
  new Word('アルバイト',  '',  'n',  'part-time job'),
  new Word('あんしん',  '安心',  'adj-na,n, vs',  'peace of mind, relief'),
  new Word('あんぜん',  '安全',  'adj-na,n',  'safety, security'),
  new Word('あんな',  '',  'adj-na,adj-pn',  'such, like that'),
  new Word('あんない・する',  '案内',  'n,vs',  'information, guidance'),
  new Word('いか',  '以下',  'n',  'less than, below'),
  new Word('いがい',  '以外',  'n',  'with the exception of, excepting'),
  new Word('いがく',  '医学',  'n',  'medical science'),
  new Word('いきる',  '生きる',  'ru-v',  'to live, to exist'),
  new Word('いくら～ても',  '',  '',  'however much one may ～'),
  new Word('いけん',  '意見',  'n',  'opinion, view'),
  new Word('いし',  '石',  'n',  'stone'),
  new Word('いじめる',  '',  'ru-v',  'to tease, to torment'),
  new Word('いじょう',  '以上',  'n-adv,n-t',  'more than, this is all'),
  new Word('いそぐ',  '急ぐ',  'u-v',  'to hurry, to rush'),
  new Word('いたす',  '致す',  'u-v',  '(hum) to do'),
  new Word('いただく',  '',  'u-v',  'to receive, to take food or drink (hum)'),
  new Word('いちど',  '一度',  'n-adv',  'once, one time'),
  new Word('いっしょうけんめい',  '一生懸命',  'adj-na,n-adv,n',  'as well as one can, with utmost effort'),
  new Word('いっぱい',  '',  'adv',  'full, to the utmost'),
  new Word('いと',  '糸',  'n,n-suf',  'thread'),
  new Word('いない',  '以内',  'n,n-suf',  'within, inside of'),
  new Word('いなか',  '田舎',  'giku n',  'rural, countryside'),
  new Word('いのる',  '祈る',  'u-v,vi',  'to pray, to wish'),
  new Word('いらっしゃる',  '',  'aru-v',  '(hon) to be, to come, to go'),
  new Word('～いん',  '～員',  'n-suf',  'member of ～'),
  new Word('うえる',  '植える',  'ru-v',  'to plant, to grow'),
  new Word('うかがう',  '',  'u-v,vi,vt',  'to visit'),
  new Word('うかがう',  '',  'u-v,vi,vt',  'to ask'),
  new Word('うけつけ',  '受付',  'n',  'reception (desk), information ガス'),
  new Word('うける',  '受ける',  'ru-v',  'to take (lesson, test), to undergo'),
  new Word('うごく',  '動く',  'u-v,vi',  'to move'),
  new Word('うそ',  '',  'n',  'lie'),
  new Word('うち',  '',  'n',  'within'),
  new Word('うつ',  '打つ',  'u-v',  'to hit, to strike'),
  new Word('うつくしい',  '美しい',  'adj',  'beautiful, lovely'),
  new Word('うつす',  '写す',  'u-v',  'copy, to photograph, to film'),
  new Word('うつる',  '移る',  'u-v',  'to move (house), to transfer (department)'),
  new Word('うで',  '腕',  'n',  'arm'),
  new Word('うまい',  '',  'adj',  'delicious'),
  new Word('うら',  '裏',  'n',  'reverse side, wrong side, back'),
  new Word('うりば',  '売り場',  'adj-no,n',  'place where things are sold'),
  new Word('うれしい',  '',  'adj',  'happy, glad'),
  new Word('うん',  '',  'n',  'yes (informal), alright'),
  new Word('うんてんしゅ',  '運転手',  'n',  'driver, chauffeur'),
  new Word('うんてん・する',  '運転',  'n,vs',  'driving'),
  new Word('うんどう・する',  '運動',  'n,vs',  'exercise'),
  new Word('エスカレーター',  '',  'n',  'escalator'),
  new Word('えだ',  '枝',  'n',  'branch, twig'),
  new Word('えらぶ',  '選ぶ',  'v5b',  'to choose, to select'),
  new Word('えんりょ・する',  '遠慮',  'adj-na,n,vs',  'restraint, reserve'),
  new Word('おいでになる',  '',  'u-v',  '(hon)to be'),
  new Word('おいわい',  'お祝い',  'n',  'congratulation, celebration'),
  new Word('オートバイ',  '',  'n',  'motorcycle (lit: auto-bi(ke))'),
  new Word('オーバー',  '',  'adj-na,n,vs',  'overcoat'),
  new Word('おかげ',  '',  'n',  'thanks or owing to'),
  new Word('おかしい',  '',  'adj',  'strange, funny'),
  new Word('～おき',  '',  '',  'after every ～'),
  new Word('おく',  '億',  'num',  '100,000,000, hundred million'),
  new Word('おくじょう',  '屋上',  'n',  'rooftop'),
  new Word('おくりもの',  '贈り物',  'n',  'present, gift'),
  new Word('おくる',  '送る',  'u-v',  'to send (a thing), to dispatch'),
  new Word('おくれる',  '遅れる',  'ru-v',  'to be late, to be delayed'),
  new Word('おこさん',  'お子さん',  'n',  '(someone elses) child'),
  new Word('おこす',  '起こす',  'u-v',  'to wake someone'),
  new Word('おこなう',  '行う',  'u-v',  'to perform, to do, to carry out'),
  new Word('おこる',  '怒る',  'u-v',  'to get angry, to be angry'),
  new Word('おしいれ',  '押し入れ',  'n',  'closet'),
  new Word('おじょうさん',  'お嬢さん',  'n',  '(1) (hon) daughter, (2) young lady'),
  new Word('おたく',  'お宅',  'n',  '(pol) your house, your home'),
  new Word('おちる',  '落ちる',  'ru-v',  'to fall, to drop'),
  new Word('おっしゃる',  '',  'aru-v',  '(hon) to say, to speak'),
  new Word('おっと',  '夫',  'n',  'husband'),
  new Word('おつり',  '',  'n',  'change (money), balance'),
  new Word('おと',  '音',  'n,n-suf',  'sound, note'),
  new Word('おとす',  '落す',  'u-v',  'to drop, to lose'),
  new Word('おどり',  '踊り',  'n',  'dance'),
  new Word('おどる',  '踊る',  'u-v',  'to dance'),
new Word('おどろく',  '驚く',  'u-v',  'to be surprised, to be astonished'),
new Word('おまつり',  'お祭り',  '',  'festival'),
new Word('おみまい',  'お見舞い',  'n',  'calling on someone who is ill, enquiry'),
new Word('おみやげ',  'お土産',  'n',  'souvenir'),
new Word('おもいだす',  '思い出す',  'u-v',  'to recall, to remember'),
new Word('おもう',  '思う',  'u-v',  'to think, to feel'),
new Word('おもちゃ',  '',  'n',  'toy'),
new Word('おもて',  '表',  'n,n-suf',  'the front, surface, exterior'),
new Word('おや',  '親',  'n',  'parents'),
new Word('おりる',  '下りる',  'ru-v',  'to descend a mountain, to (descend) go down stairs'),
new Word('おる',  '',  'u-v',  'to be (polite version of いる)'),
new Word('おる',  '折る',  'u-v',  'to break, to fold, to pick a flower'),
new Word('おれい',  'お礼',  'n',  'thanking, expression of gratitude'),
new Word('おれる',  '折れる',  'ru-v,vi,vt',  'to break, to be folded, to give in, to turn (a corner)'),
new Word('おわり',  '終わり',  'n',  'the end'),
new Word('～おわる',  '',  'suf',  'end of ～'),
new Word('～か',  '～家',  '',  'professional ～'),
new Word('カーテン',  '',  'n',  'curtain'),
new Word('～かい',  '～会',  '',  '～ meeting'),
new Word('かいがん',  '海岸',  'n',  'coast, beach'),
new Word('かいぎ',  '会議',  'n',  'meeting, conference'),
new Word('かいぎしつ',  '会議室',  'n',  'conference room'),
new Word('かいじょう',  '会場',  'n',  'assembly hall, meeting place, the grounds'),
new Word('かいわ',  '会話',  'n',  'conversation'),
new Word('かえり',  '帰り',  'n',  'return, coming back'),
new Word('かえる',  '変える',  'ru-v,vt',  'to change, to alter, to vary'),
new Word('かがく',  '科学',  'n',  'science'),
new Word('かがみ',  '鏡',  'n',  'mirror'),
new Word('～がくぶ',  '～学部',  '',  'department of a university'),
new Word('かける',  '掛ける',  '',  'to hang, to put on (eg wall)'),
new Word('かける',  '',  '',  'to sit down'),
new Word('かける',  '',  '',  'to begin to'),
new Word('かざる',  '飾る',  'u-v',  'to decorate, to ornament, to adorn'),
new Word('かじ',  '火事',  'n',  'fire'),
new Word('ガス',  '',  'n',  'gas'),
new Word('ガソリン',  '',  'n',  'gasoline, petrol'),
new Word('ガソリンスタンド',  '',  'n',  'gasoline stand, gas station, petrol station'),
new Word('かた',  '方',  'n-suf',  'way of doing'),
new Word('かたい',  '堅/硬/固い',  'adj',  'solid, hard, firm'),
new Word('かたち',  '形',  'n',  'shape'),
new Word('かたづける',  '片付ける',  'ru-v',  'to tidy up, to put in order, to put away'),
new Word('かちょう',  '課長',  'n',  'section manager'),
new Word('かつ',  '勝つ',  'u-v',  'to win, to gain victory'),
new Word('かっこう',  '',  'no--adj, na-adj',  'appearance, manner'),
new Word('かない',  '家内',  'n',  'housewife'),
new Word('かなしい',  '悲しい',  'adj',  'sad, sorrowful'),
new Word('かならず',  '必ず',  'adv',  'certainly, necessarily, invariably'),
new Word('かねもち/おかねもち',  'お・金持ち',  'n',  'rich man'),
new Word('かのじょ',  '彼女',  'n',  'she, girl-friend'),
new Word('かべ',  '壁',  'n',  'wall'),
new Word('かまう',  '',  'u-v',  'to mind, to care about'),
new Word('かみ',  '髪',  'n',  'hair'),
new Word('かむ',  '噛む',  'u-v',  'to bite, to chew'),
new Word('かよう',  '通う',  'u-v',  '(1) to go back and forth, (2) to commute'),
new Word('ガラス',  '',  'n',  'glass, pane'),
new Word('かれ',  '彼',  'n',  'he, boyfriend'),
new Word('かれら',  '彼ら',  'n',  'they (usually male)'),
new Word('かわく',  '乾く',  'u-v,vi',  'to get dry'),
new Word('かわり',  '代わり',  'n',  'substitute, alternate'),
new Word('かわる',  '変わる',  'u-v,vi',  'to change, to be transformed, to vary'),
new Word('かんがえる',  '考える',  'ru-v',  'to consider'),
new Word('かんけい',  '関係',  'n,vs',  'relation, connection'),
new Word('かんごふ',  '看護婦',  'n',  '(female) nurse'),
new Word('かんたん',  '簡単',  'adj-na,n',  'simple'),
new Word('がんばる',  '頑張る',  'u-v',  'to try ones best, to persist'),
new Word('き',  '気',  'n',  'spirit, mood'),
new Word('きかい',  '機会',  'n',  'chance, opportunity'),
new Word('きけん',  '危険',  'adj-na,n',  'danger, peril, hazard'),
new Word('きこえる',  '聞こえる',  'ru-v',  'to be heard, to be audible'),
new Word('きしゃ',  '汽車',  'n',  'train (steam)'),
new Word('ぎじゅつ',  '技術',  'n',  'art, technique, technology, skill'),
new Word('きせつ',  '季節',  'n',  'season'),
new Word('きそく',  '規則',  'n',  'rule, regulations'),
new Word('きっと',  '',  'adv,n',  'surely, definitely'),
new Word('きぬ',  '絹',  'n',  'silk'),
new Word('きびしい',  '厳しい',  'adj',  'strict'),
new Word('きぶん',  '気分',  'n',  'feeling, mood'),
new Word('きまる',  '決る',  'u-v',  'to be decided, to be settled'),
new Word('きみ',  '君',  'n,suf',  'You (masculine term for female)'),
new Word('きめる',  '決める',  'ru-v',  'to decide'),
new Word('きもち',  '気持ち',  'n',  'feeling, sensation, mood'),
new Word('きもの',  '着物',  'n',  'kimono'),
new Word('きゃく',  '客',  'n',  'guest, customer'),
new Word('きゅう',  '急',  'adj-na,n',  '(1) urgent, sudden, (2) steep'),
new Word('きゅうこう',  '急行',  'n',  'express (eg train that bypasses stations)'),
new Word('きょういく',  '教育',  'adj-no,n,vs',  'training, education'),
new Word('きょうかい',  '教会',  'n',  'church'),
new Word('きょうそう',  '競争',  'n,vs',  'competition, contest'),
new Word('きょうみ',  '興味',  'n',  'interest (in something)'),
new Word('きんじょ',  '近所',  'n',  'neighbourhood'),
new Word('～く',  '～区',  'n',  'district ～'),
new Word('ぐあい',  '具合',  'n',  'condition, state, health'),
new Word('くうき',  '空気',  'n',  'air, atmosphere'),
new Word('くうこう',  '空港',  'n',  'airport'),
new Word('くさ',  '草',  'n',  'grass'),
new Word('くださる',  '',  'aru-v',  '(hon) to give, to confer'),
new Word('くび',  '首',  'n',  'neck'),
new Word('くも',  '雲',  'n',  'cloud'),
new Word('くらべる',  '比べる',  'ru-v',  'to compare'),
new Word('くれる',  '',  'ru-v',  'to give, to do for'),
new Word('くれる',  '暮れる',  'ru-v',  'to get dark, to come to an end'),
new Word('～くん',  '～君',  'n-suf',  'Mr (junior) ～, master ～'),
new Word('け',  '毛',  'n',  'hair'),
new Word('け',  '毛',  'n',  'fur'),
new Word('けいかく・する',  '計画',  'n,vs',  'plan, project, schedule'),
new Word('けいけん・する',  '経験',  'n,vs',  'experience'),
new Word('けいざい',  '経済',  'n',  'economics, finance, economy'),
new Word('けいさつ',  '警察',  'n',  'police'),
new Word('けが・する',  '',  'n,vs',  'injury (to animate object), hurt'),
new Word('ケーキ',  '',  'n',  'cake'),
new Word('けしき',  '景色',  'n',  'scenery, scene, landscape'),
new Word('けしゴム',  '消しゴム',  'n',  'eraser'),
new Word('げしゅく',  '下宿',  'n,vs',  'boarding, lodging, boarding house'),
new Word('けっして',  '決して',  'adv',  'never'),
new Word('けれど/けれども',  '',  'conj',  'but, however'),
new Word('～けん',  '～軒',  '',  'counter for houses'),
new Word('げんいん',  '原因',  'n',  'cause, origin, source'),
new Word('けんか・する',  '',  'n',  'quarrel'),
new Word('げんかん',  '玄関',  'n',  'entrance way (in Japanese house)'),
new Word('けんきゅう',  '研究',  'n,vs',  'study, research, investigation'),
new Word('けんきゅうしつ',  '研究室',  'n',  'study room, laboratory'),
new Word('けんぶつ',  '見物',  'n',  'a sight, an attraction'),
new Word('こ',  '子',  'n',  'child'),
new Word('ご～',  '御～',  'prefix',  'honourable ～'),
new Word('こう',  '',  'adv,int-n',  'like this, this way'),
new Word('こうがい',  '郊外',  'n',  'suburb, outskirts'),
new Word('こうぎ',  '講義',  'n,vs',  'lecture'),
new Word('こうぎょう',  '工業',  'n',  '(manufacturing) industry'),
new Word('こうこう/こうとうがっこう',  '高校/高等学校',  'n',  'high school/senior high school'),
new Word('こうこうせい',  '高校生',  'n',  'high school student'),
new Word('こうじょう',  '工場',  'n',  'factory'),
new Word('こうちょう',  '校長',  'n',  'principal, headmaster'),
new Word('こうつう',  '交通',  'n',  'traffic, transportation'),
new Word('こうどう',  '講堂',  'n',  'auditorium'),
new Word('こうむいん',  '公務員',  'n',  'government worker, public servant'),
new Word('こくさい',  '国際',  'n',  'international'),
new Word('こころ',  '心',  'n',  'core, heart'),
new Word('～ございます',  '',  'expr',  'to be (polite), to exist'),
new Word('ごしゅじん',  'ご主人',  'n',  'your husband, her husband'),
new Word('こしょう・する',  '故障',  'n,vs',  'break-down'),
new Word('ごぞんじ',  'ご存じ',  'n',  'knowing, acquaintance'),
new Word('こたえ',  '答',  'n',  'answer, response'),
new Word('ごちそう',  '',  'n,vs',  'feast, treating (someone)'),
new Word('こっち',  '',  'n',  '(1) this person, (2) this direction, (3) this side, (4) thereafter'),
new Word('こと',  '',  'n',  'thing, matter, fact'),
new Word('ことり',  '小鳥',  'n',  'small bird'),
new Word('このあいだ',  '',  'n-adv',  'the other day, recently'),
new Word('このごろ',  '',  '',  'these days, nowadays'),
new Word('こまかい',  '細かい',  'adj',  '(1) small, (2) fine, minute'),
new Word('ごみ',  '',  'n',  'rubbish, trash, garbage'),
new Word('こむ',  '込む',  'u-v',  'to be crowded'),
new Word('こめ',  '米',  'n',  'uncooked rice'),
new Word('ごらんになる',  '',  '',  '(hon) to see'),
new Word('これから',  '',  'n-t',  'after this'),
new Word('こわい',  '怖い',  'adj',  'scary, frightening'),
new Word('こわす',  '壊す',  'u-v,vt',  'to break, to break down'),
new Word('こわれる',  '壊れる',  'ru-v,vi',  'to be broken, to break'),
new Word('コンサート',  '',  'n',  'concert'),
new Word('こんど',  '今度',  'n-adv,n-t',  'now, next time'),
new Word('コンピュータ/コンピューター',  '',  'n',  'computer'),
new Word('こんや',  '今夜',  'n-adv,n-t',  'this evening, tonight'),
new Word('さいきん',  '最近',  'adj-no,n-adv,n-t',  'latest, most recent, nowadays'),
new Word('さいご',  '最後',  'n',  'last, end, conclusion'),
new Word('さいしょ',  '最初',  'adj-no,n-adv,n-t',  'beginning, first'),
new Word('さか',  '坂',  'n',  'slope, hill'),
new Word('さがす',  '探す',  'u-v',  'to search, to seek, to look for'),
new Word('さがる',  '下る',  'u-v',  'to get down, to descend'),
new Word('さかん',  '盛ん',  'adj-na,n',  'popularity, prosperous'),
new Word('さげる',  '下げる',  'ru-v',  'to hang, to lower, to move back'),
new Word('さしあげる',  '差し上げる',  'ru-v',  '(polite) to give, to offer'),
new Word('さっき',  '',  'n',  'some time ago'),
new Word('さびしい',  '寂しい',  'adj',  'lonely, lonesome'),
new Word('～さま',  '～様',  'n-suf',  'Mr or Mrs ～'),
new Word('さらいげつ',  'さ来月',  '',  'the month after next'),
new Word('さらいしゅう',  'さ来週',  'n-adv,n-t',  'the week after next'),
new Word('サラダ',  '',  'n',  'salad'),
new Word('さわぐ',  '騒ぐ',  'u-v',  'to make noise, to clamor, to be excited'),
new Word('さわる',  '触る',  'u-v',  'to touch, to feel'),
new Word('さんぎょう',  '産業',  'n',  'industry'),
new Word('サンダル',  '',  'n',  'sandal'),
new Word('サンドイッチ',  '',  'n',  'sandwich'),
new Word('ざんねん',  '残念',  'adj-na,n',  'bad luck, disappointment'),
new Word('し',  '市',  'n',  'city'),
new Word('じ',  '字',  'n',  'character, hand-writing'),
new Word('しあい',  '試合',  'n',  'match, game, contest'),
new Word('しかた',  '仕方',  'n',  'way, method'),
new Word('しかる',  '',  'u-v',  'to scold'),
new Word('～しき',  '～式',  '',  'ceremony'),
new Word('しけん',  '試験',  'n,vs',  'examination, test, study'),
new Word('じこ',  '事故',  'n',  'accident'),
new Word('じしん',  '地震',  'n',  'earthquake'),
new Word('じだい',  '時代',  'n-t',  'period, epoch, era'),
new Word('したぎ',  '下着',  'n',  'underwear'),
new Word('したく・する',  '支度',  'n,vs',  'preparation'),
new Word('しっかり',  '',  'adj-na,adv,n',  'firmly, tightly, steady'),
new Word('しっぱい',  '失敗',  'adj-no,n,vs',  'failure, mistake, blunder'),
new Word('しつれい',  '失礼',  'adj-na,int,n,vs,exp',  '(1) discourtesy, impoliteness, (2) Excuse me, Goodbye'),
new Word('じてん',  '辞典',  'n',  'dictionary'),
new Word('しなもの',  '品物',  'n',  'goods'),
new Word('しばらく',  '',  'adv,int',  'little while'),
new Word('しま',  '島',  'n',  'island'),
new Word('（～て）しまう',  '',  'u-v',  'to end up ～'),
new Word('しみん',  '市民',  'n',  'citizen'),
new Word('じむしょ',  '事務所',  'n',  'office'),
new Word('しゃかい',  '社会',  'n',  'society, public'),
new Word('しゃちょう',  '社長',  'n',  'company president, manager, director'),
new Word('じゃま',  '',  'adj-na,n,vs',  'hindrance, intrusion'),
new Word('ジャム',  '',  'n',  'jam'),
new Word('じゆう',  '自由',  'adj-na,exp,n',  'freedom'),
new Word('しゅうかん',  '習慣',  'n',  'custom, habit, manners'),
new Word('じゅうしょ',  '住所',  'n',  'address (eg of house), residence, domicile'),
new Word('じゅうどう',  '柔道',  'n',  'judo'),
new Word('じゅうぶん',  '十分',  '',  'enough , sufficient'),
new Word('しゅっせき・する',  '出席',  'n,vs',  'attendance, presence'),
new Word('しゅっぱつ・する',  '出発',  'n,vs',  'departure'),
new Word('しゅみ',  '趣味',  'n',  'hobby'),
new Word('じゅんび・する',  '準備',  'n',  'prepare'),
new Word('しょうかい',  '紹介',  'n,vs',  'introduction'),
new Word('しょうがつ',  '正月',  'n',  'New Year, New Years Day'),
new Word('しょうがっこう',  '小学校',  'n',  'primary school, elementary school'),
new Word('しょうせつ',  '小説',  'n',  'novel, story'),
new Word('しょうたい・する',  '招待',  'n,vs',  'invitation'),
new Word('しょうち・する',  '承知',  'n,vs',  'consent, acceptance'),
new Word('しょうらい',  '将来',  'n-adv,n-t',  'future, prospects'),
new Word('しょくじ・する',  '食事',  'n,vs',  'meal'),
new Word('しょくりょうひん',  '食料品',  'n',  'foodstuff, groceries'),
new Word('じょせい',  '女性',  'n',  'woman'),
new Word('しらせる',  '知らせる',  'ru-v',  'to notify, to advise'),
new Word('しらべる',  '調べる',  'ru-v,vt',  'to investigate, to check up'),
new Word('じんこう',  '人口',  'n',  'population'),
new Word('じんじゃ',  '神社',  'n',  'Shinto shrine'),
new Word('しんせつ',  '親切',  'adj-na,n',  'kindness, gentleness'),
new Word('しんぱい・する',  '心配',  'adj-na,n,vs',  'worry, concern'),
new Word('しんぶんしゃ',  '新聞社',  'n',  'newspaper company'),
new Word('すいえい',  '水泳',  'n,vs',  'swimming'),
new Word('すいどう',  '水道',  'n',  'water service, water supply'),
new Word('ずいぶん',  '',  'adj-na,n-adv',  'extremely'),
new Word('すうがく',  '数学',  'n',  'mathematics, arithmetic'),
new Word('スーツ',  '',  'n',  'suit'),
new Word('スーツケース',  '',  'n',  'suitcase'),
new Word('スーパー（マーケット）',  '',  'n',  'super (market)'),
new Word('すぎる',  '過ぎる',  'ru-v,vi',  'to exceed, to go beyond'),
new Word('すく',  '',  'u-v,vi',  'to become empty'),
new Word('すく',  '',  'u-v,vi',  'to be less crowded'),
new Word('スクリーン',  '',  'n',  'screen'),
new Word('すごい',  '凄い',  'adj',  'terrific, amazing, to a great extent'),
new Word('すすむ',  '進む',  'u-v',  'to make progress, to advance, to proceed'),
new Word('すっかり',  '',  'adv',  'all, completely, thoroughly'),
new Word('ずっと',  '',  'adv,n',  'straight, quickly, all of a sudden'),
new Word('ステーキ',  '',  'n',  'steak'),
new Word('ステレオ',  '',  'n',  'stereo'),
new Word('すてる',  '捨てる',  'ru-v',  'to throw away'),
new Word('すな',  '砂',  'n',  'sand'),
new Word('すばらしい',  '',  'adj',  'wonderful, splendid'),
new Word('すべる',  '滑る',  'u-v',  'to slide, to slip'),
new Word('すみ',  '隅',  'n,n-suf',  'corner, nook'),
new Word('すむ',  '済む',  'u-v',  'to finish, to end'),
new Word('すり',  '',  'n',  'pickpocket'),
new Word('すると',  '',  'conj',  'and, then'),
new Word('～せい',  '～製',  '',  'made in　～'),
new Word('せいかつ・する',  '生活',  'n,vs',  'living, life (ones daily existence), livelihood'),
new Word('せいさん・する',  '生産',  'ru-v,vi',  'production, manufacture'),
new Word('せいじ',  '政治',  'n',  'politics, government'),
new Word('せいよう',  '西洋',  'n',  'the west, Western countries'),
new Word('せかい',  '世界',  'n',  'the world'),
new Word('せき',  '席',  'n',  'seat'),
new Word('せつめい',  '説明',  'n,vs',  'explanation'),
new Word('せなか',  '背中',  'n',  'back (of body)'),
new Word('ぜひ',  '',  'adv,n',  'certainly, without fail'),
new Word('せわ・する',  '世話',  'n,vs',  'looking after, help'),
new Word('せん',  '線',  'n,n-suf',  'line, wire'),
new Word('ぜんぜん',  '',  'adv',  'wholly, entirely'),
new Word('せんそう',  '戦争',  'n,vs',  'war'),
new Word('せんぱい',  '先輩',  'n',  'senior, superior, elder'),
new Word('せんもん',  '専門',  'n',  'speciality, study major'),
new Word('そう',  '',  'adv',  'really'),
new Word('そうだん・する',  '相談',  'n,vs',  'consultation, discussion'),
new Word('そだてる',  '育てる',  'ru-v,vt',  'to raise, to rear, to bring up'),
new Word('そつぎょう',  '卒業',  'n,vs',  'graduation'),
new Word('そふ',  '祖父',  'n',  'grandfather'),
new Word('ソフト',  '',  'n',  'soft'),
new Word('そぼ',  '祖母',  'n',  'grandmother'),
new Word('それで',  '',  'conj',  'and, thereupon, because of that'),
new Word('それに',  '',  'conj',  'besides, moreover'),
new Word('それほど',  '',  'adv',  'to that degree, extent'),
new Word('そろそろ',  '',  'n',  'gradually, steadily, soon'),
new Word('そんな',  '',  'adj-na,adj-pn,adv,n',  'such, like that, that sort of'),
new Word('そんなに',  '',  'uk',  'so much, like that'),
new Word('～だい',  '～代',  '',  '～ age/period'),
new Word('たいいん・する',  '退院',  'n,vs',  'leaving hospital'),
new Word('だいがくせい',  '大学生',  'n',  'college student, university student'),
new Word('だいじ',  '大事',  'adj-na,n',  'important, valuable, serious matter'),
new Word('だいたい',  '大体',  'n',  'generally, substantially'),
new Word('たいてい',  '',  'adj-na,adv,n',  'generally, usually'),
new Word('タイプ',  '',  'n',  'type, style'),
new Word('だいぶ',  '大分',  'adv',  'considerably, greatly, a lot'),
new Word('たいふう',  '台風',  'n',  'typhoon'),
new Word('たおれる',  '倒れる',  'ru-v,vi',  'to collapse, to break down'),
new Word('だから',  '',  'conj,n',  'so, therefore'),
new Word('たしか',  '確か',  'adj-na,adv,exp,n',  'certain, sure, definite'),
new Word('たす',  '足す',  'u-v',  'to add (numbers), to do (eg. ones business)'),
new Word('～だす',  '',  '',  'start to ～'),
new Word('たずねる',  '訪ねる',  'ru-v',  'to visit'),
new Word('たずねる',  '尋ねる',  'ru-v',  'to ask'),
new Word('ただしい',  '正しい',  'adj',  'right, just, correct'),
new Word('たたみ',  '畳',  'n',  'tatami mat (Japanese straw mat)'),
new Word('～だて',  '建て',  'n',  'two storied, separate housing'),
new Word('たてる',  '立てる',  'ru-v',  'to stand (something) up, to erect (something)'),
new Word('たてる',  '建てる',  'ru-v',  'to build, to construct'),
new Word('たとえば',  '例えば',  'adv',  'for example, eg.'),
new Word('たな',  '棚',  'n',  'shelves, rack'),
new Word('たのしむ',  '楽む',  'u-v',  'to enjoy oneself'),
new Word('たのしみ',  '楽しみ',  'n',  'pleasure, joy'),
new Word('たまに',  '',  'adv,suf',  'occasionally, once in a while'),
new Word('ため',  '為',  'n',  'good, advantage, in order to'),
new Word('だめ',  '',  'adj-na,n',  'useless, no good, hopeless'),
new Word('たりる',  '足りる',  'ru-v',  'to be sufficient, to be enough'),
new Word('だんせい',  '男性',  'n',  'male, man'),
new Word('だんぼう',  '暖房',  'n',  'heating'),
new Word('ち',  '血',  'n',  'blood'),
new Word('チェック・する',  '',  'n',  'check'),
new Word('ちから',  '力',  'n-suf',  'strength, power'),
new Word('ちっとも',  '',  'adv',  'not at all (neg. verb)'),
new Word('～ちゃん',  '',  'n',  'suffix for familiar (female) person'),
new Word('ちゅうい',  '注意',  'n,vs',  'caution, being careful, attention (heed)'),
new Word('ちゅうがっこう',  '中学校',  'n',  'junior high school, middle school pupil'),
new Word('ちゅうしゃ',  '注射',  'n,vs',  'injection'),
new Word('ちゅうしゃじょう',  '駐車場',  'n',  'parking lot, parking place'),
new Word('～ちょう',  '～町',  'n',  '～ of the town'),
new Word('ちり',  '地理',  'n',  'geography'),
new Word('～（に）ついて',  '',  'expr',  'about, concerning, regarding'),
new Word('つかまえる',  '捕まえる',  'ru-v',  'to catch, to arrest, to seize'),
new Word('つき',  '',  'n-suf',  'moon'),
new Word('～つき',  '～月',  'n-temp',  'month'),
new Word('つく',  '点く',  'u-v, intrans-verb',  'to be started, to be switched on'),
new Word('つける',  '',  'ru-v',  'to take'),
new Word('つける',  '漬ける',  'ru-v',  'to soak, to moisten, to pickle'),
new Word('つごう',  '都合',  'adv,n',  'circumstances, condition, convenience'),
new Word('つたえる',  '伝える',  'ru-v',  'to tell, to report'),
new Word('つづく',  '続く',  'u-v,vi',  'to be continued'),
new Word('～つづける',  '～続ける',  'ru-v,vt',  'to continue doing ～'),
new Word('つづける',  '続ける',  'ru-v,vt',  'to continue, to keep up, to keep on'),
new Word('つつむ',  '包む',  'u-v',  'wrap, pack'),
new Word('つま',  '妻',  'n',  '(hum) wife'),
new Word('つもり',  '',  'n',  'intention, plan'),
new Word('つる',  '釣る',  'u-v',  'to fish'),
new Word('つれる',  '連れる',  'ru-v',  'to lead, to take (a person)'),
new Word('ていねい',  '丁寧',  'adj-na,n',  'polite, courteous'),
new Word('テキスト',  '',  'n',  '(1)text, (2)text book'),
new Word('てきとう',  '適当',  'adj-na,n',  'fitness, suitability'),
new Word('できる',  '',  'ru-v',  'to be able to do'),
new Word('できるだけ',  '',  '',  'if at all possible, as much as possible'),
new Word('てつだう',  '手伝う',  'u-v',  'to help, to assist, to take part in'),
new Word('テニス',  '',  'n',  'tennis'),
new Word('てぶくろ',  '手袋',  'n',  'glove'),
new Word('てら',  '寺',  'n',  'temple'),
new Word('てん',  '点',  'n,n-suf',  'spot, mark, point, dot'),
new Word('てんいん',  '店員',  'n',  'shop assistant, employee, clerk, salesperson'),
new Word('てんきよほう',  '天気予報',  '',  'weather forecast, weather report'),
new Word('でんとう',  '電灯',  'n',  'electric light'),
new Word('でんぽう',  '電報',  'n',  'telegram'),
new Word('てんらんかい',  '展覧会',  'n',  'exhibition'),
new Word('と',  '都',  'n',  'metroplitan, municipal'),
new Word('どうぐ',  '道具',  'n',  'tool, means'),
new Word('とうとう',  '',  '',  'finally, at last'),
new Word('どうぶつえん',  '動物園',  'n',  'zoo'),
new Word('とおく',  '遠く',  'adj-no,n-adv,n',  'far away, distant'),
new Word('とおり',  '通り',  'n-suf',  '～ Street, ～ Avenue'),
new Word('とおる',  '通る',  'u-v',  'to pass (by), to go through'),
new Word('とくに',  '特に',  'adv',  'particularly, especially'),
new Word('とくべつ',  '特別',  'adj-na,adv,n',  'special'),
new Word('とこや',  '',  'n',  'barber'),
new Word('とちゅう',  '途中',  'n-adv,n-t',  'on the way, en route, midway'),
new Word('とっきゅう',  '特急',  'n',  'limited express (train, faster than an express)'),
new Word('とどける',  '届ける',  'ru-v',  'to reach'),
new Word('とまる',  '泊まる',  'u-v',  'to stay at (eg. hotel)'),
new Word('とめる',  '止める',  'ru-v,vt',  'to stop (something)'),
new Word('とりかえる',  '取り替える',  'ru-v',  'to exchange, to replace'),
new Word('どろぼう',  '泥棒',  'n,vs',  'thief, burglar, robber'),
new Word('どんどん',  '',  'adv',  'steadily, little by little'),
new Word('なおす',  '直す',  'u-v,vt',  'to fix, to repair'),
new Word('なおる',  '直る',  'u-v,vi',  'to be fixed, to be repaired'),
new Word('なおる',  '治る',  'u-v,vi',  'to be cured, to heal'),
new Word('なかなか',  '中々',  'adv',  'very, considerably, quite'),
new Word('なく',  '泣く',  'u-v',  'to cry, to weep'),
new Word('なくなる',  '無くなる',  'u-v',  'to disappear, to get lost'),
new Word('なくなる',  '亡くなる',  'u-v',  'to die'),
new Word('なげる',  '投げる',  'ru-v',  'to throw, to cast away'),
new Word('なさる',  '',  'aru-v',  '(hon) to do'),
new Word('なる',  '鳴る',  'u-v',  'to sound, to ring, to resound'),
new Word('なるべく',  '',  'adv',  'as much as possible'),
new Word('なるほど',  '',  'adv,exp',  'I see, now I understand'),
new Word('なれる',  '慣れる',  'ru-v',  'to grow accustomed to'),
new Word('におい',  '',  'ru-v',  'odour, scent, smell'),
new Word('にがい',  '苦い',  'adj',  'bitter'),
new Word('～にくい',  '',  'suf',  'difficult to do ～'),
new Word('にげる',  '逃げる',  'ru-v',  'to escape, to run away'),
new Word('にっき',  '日記',  'n',  'diary, journal'),
new Word('にゅういん・する',  '入院',  'n,vs',  'hospitalization'),
new Word('にゅうがく・する',  '入学',  'n',  'entry to school or university, matriculation'),
new Word('にる',  '似る',  'ru-v',  'to resemble, to be similar'),
new Word('にんぎょう',  '人形',  'n',  'doll, puppet, figure'),
new Word('ぬすむ',  '盗む',  'u-v',  'to steal'),
new Word('ぬる',  '塗る',  'u-v',  'to paint, to plaster'),
new Word('ぬれる',  '',  'ru-v',  'to get wet'),
new Word('ねだん',  '',  'n',  'price, cost'),
new Word('ねつ',  '熱',  'n,n-suf',  'fever, temperature'),
new Word('ねっしん',  '',  'adj-na,n',  'zeal, enthusiasm'),
new Word('ねぼう',  '寝坊',  'n,vs',  'sleeping in late'),
new Word('ねむい',  '眠い',  'adj',  'sleepy, drowsy'),
new Word('ねむる',  '眠る',  'u-v',  'to sleep'),
new Word('のこる',  '残る',  'u-v',  'to remain, to be left'),
new Word('のど',  '',  'n',  'throat'),
new Word('のりかえる',  '乗り換える',  'ru-v',  'to transfer (trains), to change (bus, train)'),
new Word('のりもの',  '乗り物',  'n',  'vehicle'),
new Word('は',  '葉',  'n',  'leaf'),
new Word('ばあい',  '場合',  'n-adv,n',  'case, situation'),
new Word('パート（タイム）',  '',  'n-adv,n',  'part time (esp female part time employees)'),
new Word('ばい',  '倍',  'n,vi,vs,vt',  'twice, double'),
new Word('はいけん・する',  '拝見',  'n,vs',  '(hum) (pol) seeing, look at'),
new Word('はいしゃ',  '歯医者',  'n',  'dentist'),
new Word('～ばかり',  '',  'suf',  'just did ～, only'),
new Word('はこぶ',  '運ぶ',  'v5b',  'to transport, to carry'),
new Word('～はじめる',  '～始める',  'ru-v,vt',  'to start doing　～, the beginning of ～'),
new Word('はじめる',  '始める',  'ru-v,vt',  'to start, to begin'),
new Word('ばしょ',  '場所',  'n',  'place, location'),
new Word('はず',  '',  'n',  'it should be so'),
new Word('はずかしい',  '恥ずかしい',  'adj',  'shy, ashamed, embarrassed'),
new Word('パソコン',  '',  'n',  '(personal) computer'),
new Word('はつおん',  '発音',  'n,vs',  'pronunciation'),
new Word('はっきり',  '',  'adv,n',  'clearly, plainly, distinctly'),
new Word('はなみ',  '花見',  'n,vs',  'cherry-blossom viewing, flower viewing'),
new Word('パパ',  '',  'n',  'papa, father'),
new Word('はやし',  '林',  'n',  'woods, forester'),
new Word('はらう',  '払う',  'u-v',  'to pay'),
new Word('ばんぐみ',  '番組',  'n',  'program (eg. TV)'),
new Word('はんたい',  '反対',  'adj-na,n,vs',  'oppose, opposition, resistance'),
new Word('ハンバーグ',  '',  'n',  'hamburger (meat, no bun)'),
new Word('ひ',  '日',  'n-adv,n-t',  'sun, sunshine, day'),
new Word('ひ',  '火',  'n,n-suf',  'fire, flame, blaze'),
new Word('ピアノ',  '',  'n',  'piano'),
new Word('ひえる',  '冷える',  'ru-v,vi',  'to grow cold, to get chilly, to cool down'),
new Word('ひかる',  '光る',  'ru-v,vi',  'to shine, to glitter'),
new Word('ひかり',  '光',  'n',  'light'),
new Word('ひきだし',  '引き出し',  'n',  'drawer, drawing out'),
new Word('ひげ',  '',  'n',  'beard'),
new Word('ひこうじょう',  '飛行場',  'n',  'airport'),
new Word('ひさしぶり',  '久しぶり',  'exp',  'after a long time'),
new Word('びじゅつかん',  '美術館',  'n',  'art gallery, art museum'),
new Word('ひじょうに',  '非常に',  'adv',  'very, extremely, exceedingly'),
new Word('びっくりする',  '',  'vs',  'to be surprised'),
new Word('ひっこす',  '引っ越す',  'u-v',  'to move, to change residence'),
new Word('ひつよう',  '必要',  'adj-na,n',  'necessary, essential'),
new Word('ひどい',  '',  'adj',  'cruel, awful'),
new Word('ひらく',  '開く',  'u-v',  'to open (eg. a festival)'),
new Word('ビル',  '',  'n',  '(abbr) building, bill'),
new Word('ひるま',  '昼間',  'n-adv,n-t',  'daytime, during the day'),
new Word('ひるやすみ',  '昼休み',  'n-adv,n-t',  'lunch break, noon recess, noon rest period'),
new Word('ひろう',  '拾う',  'u-v',  'to pick up, to find, to gather'),
new Word('ファックス',  '',  'ru-v,vi',  'fax'),
new Word('ふえる',  '増える',  'ru-v,vi',  'to increase, to multiply'),
new Word('ふかい',  '深い',  'adj',  'deep, profound, thick'),
new Word('ふくざつ',  '複雑',  'adj-na,n',  'complexity, complication'),
new Word('ふくしゅう',  '復習',  'n,vs',  'review, revision'),
new Word('ぶちょう',  '部長',  'adjn',  'head of a section'),
new Word('ふつう',  '普通',  'adj-na,adj-no,adv,n',  '(1) generally, ordinarily, usually, (2) train that stops at every station'),
new Word('ぶどう',  '',  'n',  'grapes'),
new Word('ふとる',  '太る',  'u-v',  'to grow fat (stout, plump), to become fat'),
new Word('ふとん',  '布団',  'n',  'bedding (Japanese style), futon'),
new Word('ふね',  '舟',  'n',  'ship, boat'),
new Word('ふべん',  '不便',  'adj-na,n',  'inconvenience'),
new Word('ふむ',  '踏む',  'u-v',  'to step on, to tread on'),
new Word('プレゼント',  '',  'n',  'present, gift'),
new Word('ぶんか',  '文化',  'n',  'culture, civilization'),
new Word('ぶんがく',  '文学',  'n',  'literature'),
new Word('ぶんぽう',  '文法',  'n',  'grammar'),
new Word('べつ',  '別',  'adj-na,n,n-suf',  'distinction, different'),
new Word('ベル',  '',  'n',  'bell'),
new Word('へん',  '変',  'adj-na,n',  'strange, odd, peculiar'),
new Word('へんじ',  '返事',  'n,vs',  'reply, answer'),
new Word('ぼうえき',  '貿易',  'n',  'trade (foreign)'),
new Word('ほうそう・する',  '放送',  'n,vs',  'broadcast, broadcasting'),
new Word('ほうりつ',  '法律',  'n',  'law'),
new Word('ぼく',  '僕',  'n',  '(male) I, manservant'),
new Word('ほし',  '星',  'n',  'star'),
new Word('ほど',  '',  'n',  'degree, extent'),
new Word('ほとんど',  '',  'n-adv,n-t',  'mostly, almost'),
new Word('ほめる',  '',  'ru-v',  'to praise'),
new Word('ほんやく',  '翻訳',  'n,vs',  'translation (written)'),
new Word('まいる',  '参る',  'u-v',  '(1) (hum) to go, to come'),
new Word('まける',  '負ける',  'ru-v',  'to lose, to be defeated'),
new Word('まじめ',  '',  'adj-na,n',  'diligent, serious'),
new Word('まず',  '',  'adv',  'first (of all), to start with'),
new Word('または',  '',  'conj,exp',  'or, otherwise'),
new Word('まちがえる',  '間違える',  'ru-v',  'to err, to make a mistake'),
new Word('まにあう',  '間に合う',  'u-v',  '(1) to be in time for'),
new Word('～まま',  '',  'n',  'as it is'),
new Word('まわり',  '周り',  'n,n-suf',  'surroundings, circulation'),
new Word('まわる',  '回る',  'u-v',  'to go around, to revolve'),
new Word('まんが',  '漫画',  'n',  'comic, cartoon'),
new Word('まんなか',  '真中',  'n',  'middle, centre'),
new Word('みえる',  '見える',  'ru-v',  'to be seen, to be in sight'),
new Word('みずうみ',  '湖',  'n',  'lake'),
new Word('みそ',  '味噌',  'n',  'miso, bean paste'),
new Word('みつかる',  '見つかる',  'u-v',  '(uk) to be found, to be discovered'),
new Word('みつける',  '見つける',  'ru-v',  'to discover, to find'),
new Word('みな',  '皆',  'adv,n',  'everyone, everybody'),
new Word('みなと',  '港',  'n',  'harbour, port'),
new Word('むかえる',  '迎える',  'u-v',  'to go out to meet'),
new Word('むかう',  '向かう',  'u-v',  'to face, to go towards'),
new Word('むかし',  '昔',  'adj-no,n-adv,n-t',  'olden days, former'),
new Word('むし',  '虫',  'n',  'insect'),
new Word('むすこ',  '息子',  'n',  '(hum) son'),
new Word('むすめ',  '娘',  'n',  '(hum) daughter'),
new Word('むり',  '無理',  'adj-na,n,vs',  'unreasonable, impossible'),
new Word('～め',  '～目',  'suf',  'number ～ sequence, ～nd/th'),
new Word('めしあがる',  '召し上がる',  'u-v',  '(pol) to eat'),
new Word('めずらしい',  '珍しい',  'adj',  'unusual, rare'),
new Word('もうしあげる',  '申し上げる',  'ru-v',  'to say, to tell'),
new Word('もうす',  '申す',  'u-v',  '(hum) to be called, to say'),
new Word('もうすぐ',  '',  'expr',  'soon, very soon'),
new Word('もし',  '',  'adv',  'if'),
new Word('もちろん',  '',  'adv',  'certainly, of course'),
new Word('もっとも',  '',  'adv',  'most, extremely'),
new Word('もどる',  '戻る',  'u-v',  'to turn back, to return'),
new Word('もめん',  '木綿',  'n',  'cotton'),
new Word('もらう',  '',  'u-v',  'to receive'),
new Word('もり',  '森',  'n',  'forest'),
new Word('やく',  '焼く',  'u-v',  'to bake, to grill'),
new Word('やくにたつ',  '役に立つ',  'u-v',  'to be helpful, to be useful'),
new Word('やくそく',  '約束',  'n,vs',  'arrangement, promise'),
new Word('やける',  '焼ける',  'ru-v,vi',  'to burn, to be roasted, to be sunburnt'),
new Word('やさしい',  '優しい',  'adj',  'kind, gentle'),
new Word('～やすい',  '',  '',  'easy to do ～'),
new Word('やせる',  '',  'ru-v',  'to become thin, to lose weight'),
new Word('やっと',  '',  'adv',  'at last, at length'),
new Word('やはり/やっぱり',  '',  'adv,exp',  'as I thought, absolutely'),
new Word('やむ',  '',  'u-v,vi',  'to cease, to stop'),
new Word('やめる',  '止める',  'ru-v',  'to end, to stop, to resign'),
new Word('やる',  '',  'u-v',  '(col)to do'),
new Word('やわらかい',  '柔らかい',  'adj',  'soft, tender'),
new Word('ゆ',  '湯',  'n',  'hot water'),
new Word('ゆうはん',  '夕飯',  'n',  'evening meal'),
new Word('ゆしゅつ・する',  '輸出',  'n,vs',  'export'),
new Word('ゆにゅう・する',  '輸入',  'n,vs',  'import'),
new Word('ゆび',  '指',  'n',  'finger'),
new Word('ゆびわ',  '指輪',  'n',  '(finger) ring'),
new Word('ゆめ',  '夢',  'n',  'dream'),
new Word('ゆれる',  '揺れる',  'ru-v',  'to shake, to sway'),
new Word('よう',  '様',  'adj-na',  'way, manner, kind'),
new Word('よう',  '用',  'n,n-suf',  'task, business, use'),
new Word('ようい',  '用意',  'n,vs',  'preparation'),
new Word('ようじ',  '用事',  'n',  'tasks, chores'),
new Word('よごれる',  '汚れる',  'ru-v',  'to get dirty, to become dirty'),
new Word('よしゅう',  '予習',  'n,vs',  'preparation for a lesson'),
new Word('よてい',  '予定',  'n,vs',  'plans, arrangement, schedule'),
new Word('よやく',  '予約',  'n,vs',  'reservation, booking'),
new Word('よる',  '寄る',  'u-v',  'to visit, to drop in'),
new Word('（～に）よると',  '',  '',  'according to ～'),
new Word('よろこぶ',  '喜ぶ',  'v5b',  'to be delighted, to be glad'),
new Word('よろしい',  '',  'adj',  '(hon) good, OK, all right'),
new Word('りゆう',  '理由',  'n',  'reason, pretext, motive'),
new Word('りよう',  '利用',  'n,vs',  'use, utilization'),
new Word('りょうほう',  '両方',  'n',  'both sides, both parties'),
new Word('りょかん',  '旅館',  'n',  'Japanese hotel, inn'),
new Word('るす',  '留守',  'n',  'absence, being away from home'),
new Word('れいぼう',  '冷房',  'n',  'cooling, air conditioning'),
new Word('れきし',  '歴史',  'n',  'history'),
new Word('レジ', '', 'n',  'register'),
new Word('レポート/リポート',  '',  'n',  'report, essay, assignment (aus)'),
new Word('れんらく',  '連絡',  'n,vs',  'communication, contact, connection'),
new Word('ワープロ',  '',  'n',  'word processor'),
new Word('わかす',  '沸かす',  'u-v,vt',  'to boil, to heat'),
new Word('わかれる',  '別れる',  'ru-v',  'to be divided, to part from, to separate'),
new Word('わく',  '沸く',  'u-v',  'to boil, to grow hot, to get excited'),
new Word('わけ',  '訳',  'n',  'meaning, reason'),
new Word('わすれもの',  '忘れ物',  'n',  'lost article, something forgotten'),
new Word('わらう',  '笑う',  'u-v',  'to laugh, to smile'),
new Word('わりあい',  '割合',  'adv,n',  'rate, ratio, percentage'),
new Word('われる',  '割れる',  'ru-v,vi',  'to break')
];

